name       : cryfs
version    : 0.10.3
release    : 5
source     :
    - https://github.com/cryfs/cryfs/releases/download/0.10.3/cryfs-0.10.3.tar.gz : 20348e6e2ff670505a14d4f8b2a9aa6104ce301d31ef50100cd03d17c1d7322b
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Cryptographic filesystem for the cloud
description: |
    CryFS encrypts your files, so you can safely store them anywhere. It works well together with cloud services like Dropbox, iCloud, OneDrive and others.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libcurl)
    - libboost-devel
build      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_TESTING=OFF \
                -DCRYFS_UPDATE_CHECKS=OFF
install    : |
    %ninja_install
